# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := AUnitPlatformIO
ARDUINO_LIBS := AUnit
include ../../../UnixHostDuino/UnixHostDuino.mk
