// See https://github.com/bxparks/AUniter/tree/develop/jenkins for
// a description of AUniter integration with Jenkins.
//
// The following variables are used:
//
//  * AUNITER_ARDUINO_BINARY - defined in the Jenkins system configuration
//  * WORKSPACE - automatically filled in by Jenkins
//  * BOARDS - defined in the "This project is parameterized" section of the
//    Jenkins Pipeline configuration
//
pipeline {
    agent { label 'master' }
    stages {
        stage('Setup') {
            steps {
                dir('AUniter') {
                    git url: 'https://github.com/bxparks/AUniter',
                        branch: 'develop'
                }
            }
        }
        stage('Verify Examples') {
            steps {
                sh "AUniter/auniter.sh --verify \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AUnit/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AUnit/examples/*"
            }
        }
        stage('Verify Tests') {
            steps {
                sh "AUniter/auniter.sh --verify \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AUnit/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AUnit/tests/*Test"
            }
        }
        // Some AUnit test case will always fail because they are verifying
        // that those tests actually fail. We can't run them through Jenkins
        // but we should periodically verify that they are correctly failing.
        /*
        stage('Test') {
            steps {
                sh "AUniter/auniter.sh --test \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AUnit/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AUnit/tests/*Test"
            }
        }
        */
    }
}
