# See https://github.com/bxparks/UnixHostDuino for documentation
# about using UnixHostDuino to compile and run AUnit tests natively on Linux or
# MacOS.

APP_NAME := Print64Test
ARDUINO_LIBS := AUnit
include ../../../UnixHostDuino/UnixHostDuino.mk
