# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Print64Test
ARDUINO_LIBS := AUnit
include ../../../EpoxyDuino/EpoxyDuino.mk
