# see https://github.com/bxparks/unixhostduino for documentation about this
# makefile to compile and run arduino programs natively on linux or macos.

APP_NAME := basic
ARDUINO_LIBS := AUnit
include ../../../UnixHostDuino/UnixHostDuino.mk
